name: Report based on issue label

on:
  issues:
    types: [opened, labeled]

jobs:
  run:
    name: Run Bot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
