name: Report based on issue label

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write

jobs:
  run:
    name: Run Bot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        uses: actions/github-script@v7
        with:
          script: |
            require("./events/issue_create/index.js")(github, context)
